---
- name: run the common init_config
  include_role:
    name: common
    tasks_from: init_config
    tags:
    - install
    - install:configuration
    - microsites

- name: create application and auth config
  template:
    src: "{{ item[0] }}.{{ item[1] }}.json.j2"
    dest: "{{ edxapp_app_dir }}/{{ item[0] }}.{{ item[1] }}.json"
    owner: "{{ edxapp_user }}"
    group: "{{ common_web_group }}"
    mode: 0640
  become: true
  with_nested:
    - "{{ service_variants_enabled }}"
    - [ 'env', 'auth' ]
  tags:
    - install
    - install:configuration
    - install:app-configuration
    - microsites
    - edxapp_cfg # Old deprecated tag, will remove when possible

- name: create auth and application yaml config
  template:
    src: "{{ item[0] }}.{{ item[1] }}.yaml.j2"
    dest: "{{ EDXAPP_CFG_DIR }}/{{ item[0] }}.{{ item[1] }}.yaml"
    owner: "{{ edxapp_user }}"
    group: "{{ common_web_group }}"
    mode: 0640
  become: true
  with_nested:
    - "{{ service_variants_enabled }}"
    - [ 'env', 'auth' ]
  tags:
    - install
    - install:configuration
    - install:app-configuration
    - microsites
    - edxapp_cfg # Old deprecated tag, will remove when possible
